apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtenants.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: XTenant
    plural: xtenants
  claimNames:
    kind: Tenant
    plural: tenants
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                quota:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                    pods:
                      type: integer
                limits:
                  type: object
                  properties:
                    defaultCpu:
                      type: string
                    defaultMemory:
                      type: string
                    maxCpu:
                      type: string
                    maxMemory:
                      type: string
