apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-level infrastructure (Crossplane + XRD + Compositions)

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: apiextensions.crossplane.io
      kind: CompositeResourceDefinition
    - group: apiextensions.crossplane.io
      kind: Composition
    - group: pkg.crossplane.io
      kind: Provider
    - group: ""
      kind: Namespace
    - group: networking.k8s.io
      kind: NetworkPolicy

  namespaceResourceWhitelist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange