apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xtenant-kubernetes
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XTenant

  mode: Pipeline

  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:

          # ---------------------------------------------------------
          # Namespace
          # ---------------------------------------------------------
          - name: namespace
            base:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: placeholder
            patches:
              - fromFieldPath: spec.namespace
                toFieldPath: metadata.name

          # ---------------------------------------------------------
          # ResourceQuota
          # ---------------------------------------------------------
          - name: quota
            base:
              apiVersion: v1
              kind: ResourceQuota
              metadata:
                name: tenant-quota
              spec:
                hard:
                  cpu: "1"
                  memory: "1Gi"
                  pods: "5"
            patches:
              - fromFieldPath: spec.namespace
                toFieldPath: metadata.namespace
              - fromFieldPath: spec.quota.cpu
                toFieldPath: spec.hard.cpu
              - fromFieldPath: spec.quota.memory
                toFieldPath: spec.hard.memory
              - fromFieldPath: spec.quota.pods
                toFieldPath: spec.hard.pods

          # ---------------------------------------------------------
          # LimitRange
          # ---------------------------------------------------------
          - name: limits
            base:
              apiVersion: v1
              kind: LimitRange
              metadata:
                name: tenant-limits
              spec:
                limits:
                  - type: Container
            patches:
              - fromFieldPath: spec.namespace
                toFieldPath: metadata.namespace
              - fromFieldPath: spec.limits.defaultCpu
                toFieldPath: spec.limits[0].default.cpu
              - fromFieldPath: spec.limits.defaultMemory
                toFieldPath: spec.limits[0].default.memory
              - fromFieldPath: spec.limits.maxCpu
                toFieldPath: spec.limits[0].max.cpu
              - fromFieldPath: spec.limits.maxMemory
                toFieldPath: spec.limits[0].max.memory

          # ---------------------------------------------------------
          # Default Deny NetworkPolicy
          # ---------------------------------------------------------
          - name: networkpolicy
            base:
              apiVersion: networking.k8s.io/v1
              kind: NetworkPolicy
              metadata:
                name: default-deny
              spec:
                podSelector: {}
                policyTypes:
                  - Ingress
                  - Egress
            patches:
              - fromFieldPath: spec.namespace
                toFieldPath: metadata.namespace
